ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue1" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue2" DECIMAL NOT NULL DEFAULT 0.01;
ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue3" DECIMAL NOT NULL DEFAULT 0.02;
ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue4" DECIMAL NOT NULL DEFAULT 0.03;
ALTER TABLE "ProjectRule" ADD COLUMN "similarExperienceScore" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "ProjectRule" ADD COLUMN "otherScore" DECIMAL NOT NULL DEFAULT 0;
