ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue1" DECIMAL(38, 20) NOT NULL DEFAULT 0;
ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue2" DECIMAL(38, 20) NOT NULL DEFAULT 0.01;
ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue3" DECIMAL(38, 20) NOT NULL DEFAULT 0.02;
ALTER TABLE "ProjectRule" ADD COLUMN "qingbiaoDrawValue4" DECIMAL(38, 20) NOT NULL DEFAULT 0.03;
ALTER TABLE "ProjectRule" ADD COLUMN "similarExperienceScore" DECIMAL(38, 20) NOT NULL DEFAULT 0;
ALTER TABLE "ProjectRule" ADD COLUMN "otherScore" DECIMAL(38, 20) NOT NULL DEFAULT 0;
