import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const canonicalSchemaPath = path.resolve("prisma/schema.prisma");
const postgresqlSchemaPath = path.resolve("prisma/postgresql/schema.prisma");

const moneyFields = new Set([
  "ProjectRule.maxBidPrice",
  "ProjectRule.nonCompetitiveFee",
  "ProjectCandidate.bidPrice",
  "QingbiaoScenario.referencePriceB",
  "QingbiaoResult.priceDifference",
  "DingbiaoScenario.benchmarkPriceM",
  "DingbiaoResult.bidPrice",
  "DingbiaoResult.differenceToM",
]);

const ratioAndScoreFields = new Set([
  "ProjectRule.totalBidPriceScore",
  "ProjectRule.qingbiaoDrawValue1",
  "ProjectRule.qingbiaoDrawValue2",
  "ProjectRule.qingbiaoDrawValue3",
  "ProjectRule.qingbiaoDrawValue4",
  "ProjectRule.similarExperienceScore",
  "ProjectRule.otherScore",
  "ProjectRule.rankDeduction",
  "ProjectRule.finalDrawValue1",
  "ProjectRule.finalDrawValue2",
  "ProjectRule.finalDrawValue3",
  "ProjectCandidate.netDiscountRate",
  "ProjectCandidate.trademarkScore",
  "ProjectCandidate.technicalScore",
  "ProjectCandidate.similarExperienceScore",
  "ProjectCandidate.otherScore",
  "CompanyPerformance.score",
  "PerformanceWeightedScore.weightedAverage",
  "QingbiaoScenario.qingbiaoK1",
  "QingbiaoResult.performanceAverage",
  "QingbiaoResult.performanceScore",
  "QingbiaoResult.priceScore",
  "QingbiaoResult.totalScore",
  "DingbiaoScenario.finalDrawValue",
  "DingbiaoScenario.dingbiaoK1",
  "DingbiaoResult.netDiscountRateSnapshot",
]);

function generatePostgresqlSchema(canonicalSchema: string): string {
  let currentModel: string | undefined;
  const mappedDecimals = new Set<string>();

  const lines = canonicalSchema.split(/\r?\n/).map((line) => {
    const modelMatch = /^model\s+(\w+)\s+\{$/.exec(line);
    if (modelMatch) {
      currentModel = modelMatch[1];
      return line;
    }

    if (line === "}") {
      currentModel = undefined;
      return line;
    }

    if (!currentModel) {
      return line;
    }

    const fieldMatch = /^(\s+)(\w+)(\s+)Decimal(\??)(.*)$/.exec(line);
    if (fieldMatch) {
      const [, indentation, fieldName, spacing, optionalMarker, attributes] = fieldMatch;
      if (!fieldName) {
        throw new Error(`Unable to parse Decimal field in line: ${line}`);
      }

      const fieldKey = `${currentModel}.${fieldName}`;
      const nativeType = moneyFields.has(fieldKey)
        ? "@db.Decimal(38, 18)"
        : ratioAndScoreFields.has(fieldKey)
          ? "@db.Decimal(38, 20)"
          : undefined;

      if (!nativeType) {
        throw new Error(`PostgreSQL precision is not classified for ${fieldKey}.`);
      }

      mappedDecimals.add(fieldKey);
      return `${indentation}${fieldName}${spacing}Decimal${optionalMarker} ${nativeType}${attributes}`;
    }

    return line.replace(/DateTime(\??)(\s+)/, "DateTime$1 @db.Timestamptz(3)$2");
  });

  const expectedDecimals = new Set([...moneyFields, ...ratioAndScoreFields]);
  const missingFields = [...expectedDecimals].filter((field) => !mappedDecimals.has(field));
  if (missingFields.length > 0) {
    throw new Error(
      `PostgreSQL precision mapping references missing fields: ${missingFields.join(", ")}`,
    );
  }

  return [
    "// AUTO-GENERATED by scripts/generate-postgresql-schema.ts.",
    "// Edit prisma/schema.prisma and the explicit precision map instead of this file.",
    "",
    ...lines,
  ]
    .join("\n")
    .replace('output   = "../src/generated/prisma"', 'output   = "../../src/generated/prisma"')
    .replace('provider = "sqlite"', 'provider = "postgresql"');
}

const canonicalSchema = await readFile(canonicalSchemaPath, "utf8");
const generatedSchema = generatePostgresqlSchema(canonicalSchema);

if (process.argv.includes("--check")) {
  const existingSchema = await readFile(postgresqlSchemaPath, "utf8").catch(() => undefined);
  if (existingSchema !== generatedSchema) {
    throw new Error(
      "Generated PostgreSQL schema is stale. Run pnpm db:schema:postgres and commit the result.",
    );
  }
} else {
  await mkdir(path.dirname(postgresqlSchemaPath), { recursive: true });
  await writeFile(postgresqlSchemaPath, generatedSchema, "utf8");
  console.info(`Generated ${path.relative(process.cwd(), postgresqlSchemaPath)}.`);
}
